# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

context: SLACK
orbs:  
  slack: circleci/slack@4.4




jobs:  
  build:
    context: 
    docker:
      - image: cimg/openjdk:11.0.17
    steps:
      - run: java -version
      -  checkout
      - run:
          name: "echo environment variables from SLACK context"
          command: echo $SLACK_ACCESS_TOKEN      
      - run:
          name: Print Project Directory
          command: |
            pwd
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install -y unzip
            curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
       # Authenticate and download .ipa file
      - run:
          name: Authenticate and download .ipa file
          command: |

      # Upload the .ipa file to BrowserStack
      - run:
          name: Upload .ipa file to BrowserStack          
          command:
      - slack/notify:
          channel: C05V416QMT5 #ID of the slack channel
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
            
                   "text": "IOS Automation execution started."
                 }
                }
              ]
            }  
                    
      - run:
          name: Install maven dependencies
          command: mvn clean verify -DbsUsername=sarikakothakona_wUEIC8 -DbsPassword=pxjQN4WzseMjsGfstfdF -DAppUserName=3125551111 -DAppPassword=hh-QA-Auto!2023F -DAppEnvironment=staging -DPlatformName=IOS -DDeviceName="iPhone 14" -DOSversion=16 -Dcucumber.filter.tags="@IOS"
      
      - store_artifacts:
          path: test-output/SparkReport
      - store_artifacts:
          path: test-output            
      - store_artifacts:
          path: test output/PdfReport
      - slack/notify:
          channel: C05V416QMT5 #ID of the slack channel
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
            
                   "text": "IOS Automation results are ready.\nBranch: `$CIRCLE_BRANCH`\nReport Link: <https://output.circle-artifacts.com/output/job/$CIRCLE_WORKFLOW_JOB_ID/artifacts/0/test-output/SparkReport/Index.html"
                 }
                }
              ]
            }    
      # - store_test_results:
      #     path: target/failsafe-reports

workflows:
  build:
    jobs :
      -  build:
            context: 
              - SLACK

